IMPORT NUMPY


In [4]:
import numpy as np

SCALARS, VECTORS, MATRICES, TENSORS

In [5]:
scalar = 10
print("Scalar:", scalar)

vector = np.array([1, 2, 3])
print("\nVector:")
print(vector)

matrix = np.array([[1, 2],
                   [3, 4]])
print("\nMatrix:")
print(matrix)

tensor = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

print("\nTensor:")
print(tensor)

Scalar: 10

Vector:
[1 2 3]

Matrix:
[[1 2]
 [3 4]]

Tensor:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


MATRIX MULTIPLICATION

In [6]:
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

print("Matrix Multiplication:")
print(np.matmul(A,B))

Matrix Multiplication:
[[19 22]
 [43 50]]


EIGENVALUES

In [7]:
matrix = np.array([[2,0],
                   [0,3]])

values, vectors = np.linalg.eig(matrix)

print("Eigenvalues:")
print(values)

print("\nEigenvectors:")
print(vectors)

Eigenvalues:
[2.+0.j 3.+0.j]

Eigenvectors:
[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]


MEAN, MEDIAN, VARIANCE, STANDARD_DEVIATION

In [ ]:
data = np.array([10,20,30,40,50])

print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Variance:", np.var(data)) #find the mean, subtarct each value from the mean, square the result, and then find the mean of those squared differences
print("Standard Deviation:", np.std(data)) #square of variance, which is the square root of the variance

Mean: 30.0
Median: 30.0
Variance: 200.0
Standard Deviation: 14.142135623730951


CORRELATION

In [10]:
x = np.array([1,2,3,4,5])
y = np.array([2,4,6,8,10])

print("Correlation Matrix:")
print(np.corrcoef(x,y))

Correlation Matrix:
[[1. 1.]
 [1. 1.]]


NORMAL DISTRIBUTION

In [11]:
data = np.random.normal(0,1,1000)

print("First 10 values:")
print(data[:10])

print("Mean:", np.mean(data))
print("Standard Deviation:", np.std(data))

First 10 values:
[ 0.65927557 -1.4264167   2.08061462 -0.9650526  -0.53599033  0.13101766
 -0.00425977 -0.20243245 -0.20339374 -0.22046138]
Mean: 0.06395889921215873
Standard Deviation: 1.0323767261552144


SIMPLE GRADIENT EXAMPLE

In [12]:
x = 3

gradient = 2 * x

print("For f(x)=x²")
print("Gradient at x=3:", gradient)

For f(x)=x²
Gradient at x=3: 6


SCALARS IN PYTHON

In [13]:
age = 20
cgpa = 9.31
temperature = 28.5

print(age)
print(cgpa)
print(temperature)

20
9.31
28.5


SCALARS IN NUMPY

In [14]:
import numpy as np

scalar = np.array(10)

print(scalar)
print(scalar.shape)
print(scalar.ndim)

10
()
0


VECTOR IN NUMPY

In [18]:
import numpy as np

vector = np.array([20, 9.31, 1])

print(vector)
print("Shape:", vector.shape)
print("Dimensions:", vector.ndim)

[20.    9.31  1.  ]
Shape: (3,)
Dimensions: 1


In [24]:
#calculate magnitude
v = np.array([[3,4]])
print(np.linalg.norm(v))

5.0


Element-Wise Vector Arithmetic in NumPy

In [25]:
A = np.array([2,3])
B = np.array([4,5])

print(A+B)
print(A-B)
print(A*B)
print(A/B)

[6 8]
[-2 -2]
[ 8 15]
[0.5 0.6]


In [32]:
#1D Array
a=np.array([10,20,30,40])
a.shape


(4,)

In [33]:
#2D Row Vector
b=np.array([[10,20,30,40]])
b.shape    

(1, 4)

MATRIX IN NUMPY

In [34]:
import numpy as np

marks = np.array([
    [90, 85, 80],
    [75, 88, 92],
    [95, 91, 89],
    [80, 84, 86]
])

print(marks)
print("Shape:", marks.shape)
print("Dimensions:", marks.ndim)

[[90 85 80]
 [75 88 92]
 [95 91 89]
 [80 84 86]]
Shape: (4, 3)
Dimensions: 2


MATRIX MULTIPLICATION

In [39]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print(A @ B)

[[19 22]
 [43 50]]
